# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

name: push
on:
  - push
permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
        with:
          experimental: true

      - uses: j178/prek-action@0bb87d7f00b0c99306c8bcb8b8beba1eb581c037 # v1.1.1
        with:
          extra-args: --skip no-commit-to-branch,zizmor

      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9
        with:
          install-mode: none
          only-new-issues: true

      - name: zizmor
        uses: zizmorcore/zizmor-action@629d5d01fe5939a6aeae25c1bd1acd2cfa28e9b2

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
        with:
          experimental: true

      - name: go mod tidy
        run: go mod tidy -diff

      - name: go build
        run: go build ./...

      - name: go test
        run: 'go tool gotestsum
          --packages="./..."
          --junitfile junit.xml
          --jsonfile gotest.json
          --
          -coverprofile=coverage.txt
          -race
          -count 100
          -parallel "$(nproc)"'

      - name: process results for summary
        if: ${{ !cancelled() }}
        uses: robherley/go-test-action@42a1975c97156330b5126c2f35ef0fb78c4c7154 # v0.7.1
        with:
          fromJSONFile: gotest.json

      - name: upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: coverage
          files: ./coverage.txt

      - name: upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          files: ./junit.xml
